package com.group12.salary.dao;

import com.group12.salary.model.ActionDAO;
import com.group12.salary.model.ActionDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActionDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    long countByExample(ActionDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int deleteByExample(ActionDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int insert(ActionDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int insertSelective(ActionDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    List<ActionDAO> selectByExample(ActionDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    ActionDAO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ActionDAO record, @Param("example") ActionDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ActionDAO record, @Param("example") ActionDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ActionDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_action
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    int updateByPrimaryKey(ActionDAO record);
}