package com.group12.salary.dao;

import com.group12.salary.model.DeductDAO;
import com.group12.salary.model.DeductDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeductDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	long countByExample(DeductDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByExample(DeductDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insert(DeductDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insertSelective(DeductDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	List<DeductDAO> selectByExample(DeductDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	DeductDAO selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") DeductDAO record, @Param("example") DeductDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") DeductDAO record, @Param("example") DeductDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(DeductDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_deduct
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKey(DeductDAO record);
}