package com.group12.salary.dao;

import com.group12.salary.model.GroupDAO;
import com.group12.salary.model.GroupDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	long countByExample(GroupDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByExample(GroupDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long groupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insert(GroupDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insertSelective(GroupDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	List<GroupDAO> selectByExample(GroupDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	GroupDAO selectByPrimaryKey(Long groupId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") GroupDAO record, @Param("example") GroupDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") GroupDAO record, @Param("example") GroupDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(GroupDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKey(GroupDAO record);
}