package com.group12.salary.dao;

import com.group12.salary.model.RoleRightDAO;
import com.group12.salary.model.RoleRightDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRightDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	long countByExample(RoleRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByExample(RoleRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long roleRightId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insert(RoleRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insertSelective(RoleRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	List<RoleRightDAO> selectByExample(RoleRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	RoleRightDAO selectByPrimaryKey(Long roleRightId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") RoleRightDAO record, @Param("example") RoleRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") RoleRightDAO record, @Param("example") RoleRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(RoleRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKey(RoleRightDAO record);
}