package com.group12.salary.dao;

import com.group12.salary.model.SalaryDAO;
import com.group12.salary.model.SalaryDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalaryDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	long countByExample(SalaryDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int deleteByExample(SalaryDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int insert(SalaryDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int insertSelective(SalaryDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	List<SalaryDAO> selectByExample(SalaryDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	SalaryDAO selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") SalaryDAO record, @Param("example") SalaryDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") SalaryDAO record, @Param("example") SalaryDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(SalaryDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_salary
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByPrimaryKey(SalaryDAO record);
}