package com.group12.salary.dao;

import com.group12.salary.model.SubsidyDAO;
import com.group12.salary.model.SubsidyDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubsidyDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	long countByExample(SubsidyDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByExample(SubsidyDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insert(SubsidyDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insertSelective(SubsidyDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	List<SubsidyDAO> selectByExample(SubsidyDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	SubsidyDAO selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") SubsidyDAO record, @Param("example") SubsidyDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") SubsidyDAO record, @Param("example") SubsidyDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(SubsidyDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKey(SubsidyDAO record);
}