package com.group12.salary.dao;

import com.group12.salary.model.UserRightDAO;
import com.group12.salary.model.UserRightDAOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRightDAOMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	long countByExample(UserRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int deleteByExample(UserRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(Long userRightId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int insert(UserRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int insertSelective(UserRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	List<UserRightDAO> selectByExample(UserRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	UserRightDAO selectByPrimaryKey(Long userRightId);
	UserRightDAO selectByUserID(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") UserRightDAO record, @Param("example") UserRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") UserRightDAO record, @Param("example") UserRightDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(UserRightDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	int updateByPrimaryKey(UserRightDAO record);
}