package com.group12.salary.dao;

import com.group12.salary.model.UserDAO;
import com.group12.salary.model.UserDAOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface UserDAOMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	long countByExample(UserDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByExample(UserDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insert(UserDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int insertSelective(UserDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	List<UserDAO> selectByExample(UserDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	UserDAO selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExampleSelective(@Param("record") UserDAO record, @Param("example") UserDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByExample(@Param("record") UserDAO record, @Param("example") UserDAOExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKeySelective(UserDAO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	int updateByPrimaryKey(UserDAO record);

	/**
     * 权限
     * @param userId
     * @return
     */
    Set<String> getRight(@Param("userId") String userId);

    /**
     * 角色
     * @param userId
     * @return
     */
    Set<String> getRole(@Param("userId") String userId);


}