package com.group12.salary.model;

import java.io.Serializable;
import java.util.Date;

public class CensusDAO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.census_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private Long censusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.start_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.end_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.page_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private String pageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.page_name
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private String pageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.user_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_census.doString
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private String dostring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_census
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.census_id
     *
     * @return the value of t_census.census_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public Long getCensusId() {
        return censusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.census_id
     *
     * @param censusId the value for t_census.census_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setCensusId(Long censusId) {
        this.censusId = censusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.start_time
     *
     * @return the value of t_census.start_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.start_time
     *
     * @param startTime the value for t_census.start_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.end_time
     *
     * @return the value of t_census.end_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.end_time
     *
     * @param endTime the value for t_census.end_time
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.page_id
     *
     * @return the value of t_census.page_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.page_id
     *
     * @param pageId the value for t_census.page_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setPageId(String pageId) {
        this.pageId = pageId == null ? null : pageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.page_name
     *
     * @return the value of t_census.page_name
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.page_name
     *
     * @param pageName the value for t_census.page_name
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.user_id
     *
     * @return the value of t_census.user_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.user_id
     *
     * @param userId the value for t_census.user_id
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_census.doString
     *
     * @return the value of t_census.doString
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public String getDostring() {
        return dostring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_census.doString
     *
     * @param dostring the value for t_census.doString
     *
     * @mbg.generated Wed Jun 03 23:05:18 GMT+08:00 2020
     */
    public void setDostring(String dostring) {
        this.dostring = dostring == null ? null : dostring.trim();
    }
}