package com.group12.salary.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ChangeDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.before_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private BigDecimal beforeMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.after_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private BigDecimal afterMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String submitUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Date submitDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_change.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_change
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.id
	 * @return  the value of t_change.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.id
	 * @param id  the value for t_change.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.user_id
	 * @return  the value of t_change.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.user_id
	 * @param userId  the value for t_change.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.name
	 * @return  the value of t_change.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.name
	 * @param name  the value for t_change.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.before_money
	 * @return  the value of t_change.before_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public BigDecimal getBeforeMoney() {
		return beforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.before_money
	 * @param beforeMoney  the value for t_change.before_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setBeforeMoney(BigDecimal beforeMoney) {
		this.beforeMoney = beforeMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.after_money
	 * @return  the value of t_change.after_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public BigDecimal getAfterMoney() {
		return afterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.after_money
	 * @param afterMoney  the value for t_change.after_money
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setAfterMoney(BigDecimal afterMoney) {
		this.afterMoney = afterMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.submit_user_id
	 * @return  the value of t_change.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getSubmitUserId() {
		return submitUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.submit_user_id
	 * @param submitUserId  the value for t_change.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setSubmitUserId(String submitUserId) {
		this.submitUserId = submitUserId == null ? null : submitUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.submit_date
	 * @return  the value of t_change.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Date getSubmitDate() {
		return submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.submit_date
	 * @param submitDate  the value for t_change.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_change.status
	 * @return  the value of t_change.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_change.status
	 * @param status  the value for t_change.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}