package com.group12.salary.model;

import java.io.Serializable;

public class CodeDAO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String stme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.msg
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.line
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.col
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String col;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.err
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String err;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.ua
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String ua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_code
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.id
     *
     * @return the value of t_code.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.id
     *
     * @param id the value for t_code.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.type
     *
     * @return the value of t_code.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.type
     *
     * @param type the value for t_code.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.path
     *
     * @return the value of t_code.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.path
     *
     * @param path the value for t_code.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.sTme
     *
     * @return the value of t_code.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getStme() {
        return stme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.sTme
     *
     * @param stme the value for t_code.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setStme(String stme) {
        this.stme = stme == null ? null : stme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.msg
     *
     * @return the value of t_code.msg
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.msg
     *
     * @param msg the value for t_code.msg
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.line
     *
     * @return the value of t_code.line
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.line
     *
     * @param line the value for t_code.line
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.col
     *
     * @return the value of t_code.col
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.col
     *
     * @param col the value for t_code.col
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setCol(String col) {
        this.col = col == null ? null : col.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.err
     *
     * @return the value of t_code.err
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getErr() {
        return err;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.err
     *
     * @param err the value for t_code.err
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setErr(String err) {
        this.err = err == null ? null : err.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.ua
     *
     * @return the value of t_code.ua
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getUa() {
        return ua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.ua
     *
     * @param ua the value for t_code.ua
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setUa(String ua) {
        this.ua = ua == null ? null : ua.trim();
    }
}