package com.group12.salary.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ErrorDAOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public ErrorDAOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andItemIsNull() {
			addCriterion("item is null");
			return (Criteria) this;
		}

		public Criteria andItemIsNotNull() {
			addCriterion("item is not null");
			return (Criteria) this;
		}

		public Criteria andItemEqualTo(String value) {
			addCriterion("item =", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotEqualTo(String value) {
			addCriterion("item <>", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemGreaterThan(String value) {
			addCriterion("item >", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemGreaterThanOrEqualTo(String value) {
			addCriterion("item >=", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemLessThan(String value) {
			addCriterion("item <", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemLessThanOrEqualTo(String value) {
			addCriterion("item <=", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemLike(String value) {
			addCriterion("item like", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotLike(String value) {
			addCriterion("item not like", value, "item");
			return (Criteria) this;
		}

		public Criteria andItemIn(List<String> values) {
			addCriterion("item in", values, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotIn(List<String> values) {
			addCriterion("item not in", values, "item");
			return (Criteria) this;
		}

		public Criteria andItemBetween(String value1, String value2) {
			addCriterion("item between", value1, value2, "item");
			return (Criteria) this;
		}

		public Criteria andItemNotBetween(String value1, String value2) {
			addCriterion("item not between", value1, value2, "item");
			return (Criteria) this;
		}

		public Criteria andWrongDataIsNull() {
			addCriterion("wrong_data is null");
			return (Criteria) this;
		}

		public Criteria andWrongDataIsNotNull() {
			addCriterion("wrong_data is not null");
			return (Criteria) this;
		}

		public Criteria andWrongDataEqualTo(BigDecimal value) {
			addCriterion("wrong_data =", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataNotEqualTo(BigDecimal value) {
			addCriterion("wrong_data <>", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataGreaterThan(BigDecimal value) {
			addCriterion("wrong_data >", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("wrong_data >=", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataLessThan(BigDecimal value) {
			addCriterion("wrong_data <", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataLessThanOrEqualTo(BigDecimal value) {
			addCriterion("wrong_data <=", value, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataIn(List<BigDecimal> values) {
			addCriterion("wrong_data in", values, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataNotIn(List<BigDecimal> values) {
			addCriterion("wrong_data not in", values, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("wrong_data between", value1, value2, "wrongData");
			return (Criteria) this;
		}

		public Criteria andWrongDataNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("wrong_data not between", value1, value2, "wrongData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataIsNull() {
			addCriterion("revised_data is null");
			return (Criteria) this;
		}

		public Criteria andRevisedDataIsNotNull() {
			addCriterion("revised_data is not null");
			return (Criteria) this;
		}

		public Criteria andRevisedDataEqualTo(BigDecimal value) {
			addCriterion("revised_data =", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataNotEqualTo(BigDecimal value) {
			addCriterion("revised_data <>", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataGreaterThan(BigDecimal value) {
			addCriterion("revised_data >", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("revised_data >=", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataLessThan(BigDecimal value) {
			addCriterion("revised_data <", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataLessThanOrEqualTo(BigDecimal value) {
			addCriterion("revised_data <=", value, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataIn(List<BigDecimal> values) {
			addCriterion("revised_data in", values, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataNotIn(List<BigDecimal> values) {
			addCriterion("revised_data not in", values, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("revised_data between", value1, value2, "revisedData");
			return (Criteria) this;
		}

		public Criteria andRevisedDataNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("revised_data not between", value1, value2, "revisedData");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIsNull() {
			addCriterion("submit_user_id is null");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIsNotNull() {
			addCriterion("submit_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdEqualTo(String value) {
			addCriterion("submit_user_id =", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotEqualTo(String value) {
			addCriterion("submit_user_id <>", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdGreaterThan(String value) {
			addCriterion("submit_user_id >", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("submit_user_id >=", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLessThan(String value) {
			addCriterion("submit_user_id <", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLessThanOrEqualTo(String value) {
			addCriterion("submit_user_id <=", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLike(String value) {
			addCriterion("submit_user_id like", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotLike(String value) {
			addCriterion("submit_user_id not like", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIn(List<String> values) {
			addCriterion("submit_user_id in", values, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotIn(List<String> values) {
			addCriterion("submit_user_id not in", values, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdBetween(String value1, String value2) {
			addCriterion("submit_user_id between", value1, value2, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotBetween(String value1, String value2) {
			addCriterion("submit_user_id not between", value1, value2, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIsNull() {
			addCriterion("submit_date is null");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIsNotNull() {
			addCriterion("submit_date is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitDateEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date =", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date <>", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateGreaterThan(Date value) {
			addCriterionForJDBCDate("submit_date >", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date >=", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateLessThan(Date value) {
			addCriterionForJDBCDate("submit_date <", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date <=", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIn(List<Date> values) {
			addCriterionForJDBCDate("submit_date in", values, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("submit_date not in", values, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("submit_date between", value1, value2, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("submit_date not between", value1, value2, "submitDate");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(int i) {
			addCriterion("status =", i, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Boolean value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Boolean value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Boolean value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Boolean value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Boolean> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Boolean> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Boolean value1, Boolean value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_error
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_error
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 21 18:01:03 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}