package com.group12.salary.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ErrorDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.item
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String item;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.wrong_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private BigDecimal wrongData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.revised_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private BigDecimal revisedData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String submitUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Date submitDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_error.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_error
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.id
	 * @return  the value of t_error.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.id
	 * @param id  the value for t_error.id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.user_id
	 * @return  the value of t_error.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.user_id
	 * @param userId  the value for t_error.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.name
	 * @return  the value of t_error.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.name
	 * @param name  the value for t_error.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.item
	 * @return  the value of t_error.item
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.item
	 * @param item  the value for t_error.item
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setItem(String item) {
		this.item = item == null ? null : item.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.wrong_data
	 * @return  the value of t_error.wrong_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public BigDecimal getWrongData() {
		return wrongData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.wrong_data
	 * @param wrongData  the value for t_error.wrong_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setWrongData(BigDecimal wrongData) {
		this.wrongData = wrongData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.revised_data
	 * @return  the value of t_error.revised_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public BigDecimal getRevisedData() {
		return revisedData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.revised_data
	 * @param revisedData  the value for t_error.revised_data
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRevisedData(BigDecimal revisedData) {
		this.revisedData = revisedData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.submit_user_id
	 * @return  the value of t_error.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getSubmitUserId() {
		return submitUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.submit_user_id
	 * @param submitUserId  the value for t_error.submit_user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setSubmitUserId(String submitUserId) {
		this.submitUserId = submitUserId == null ? null : submitUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.submit_date
	 * @return  the value of t_error.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Date getSubmitDate() {
		return submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.submit_date
	 * @param submitDate  the value for t_error.submit_date
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_error.status
	 * @return  the value of t_error.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_error.status
	 * @param status  the value for t_error.status
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}