package com.group12.salary.model;

import java.io.Serializable;

public class GroupRoleDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_role.group_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long groupRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_role.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_group_role
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_role.group_role_id
	 * @return  the value of t_group_role.group_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getGroupRoleId() {
		return groupRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_role.group_role_id
	 * @param groupRoleId  the value for t_group_role.group_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setGroupRoleId(Long groupRoleId) {
		this.groupRoleId = groupRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_role.group_id
	 * @return  the value of t_group_role.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_role.group_id
	 * @param groupId  the value for t_group_role.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_role.role_id
	 * @return  the value of t_group_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_role.role_id
	 * @param roleId  the value for t_group_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}