package com.group12.salary.model;

import java.io.Serializable;

public class GroupRightDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_right.group_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long groupRightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_right.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long rightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Boolean rightType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_group_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_right.group_right_id
	 * @return  the value of t_group_right.group_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getGroupRightId() {
		return groupRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_right.group_right_id
	 * @param groupRightId  the value for t_group_right.group_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setGroupRightId(Long groupRightId) {
		this.groupRightId = groupRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_right.group_id
	 * @return  the value of t_group_right.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_right.group_id
	 * @param groupId  the value for t_group_right.group_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_right.right_id
	 * @return  the value of t_group_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_right.right_id
	 * @param rightId  the value for t_group_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group_right.right_type
	 * @return  the value of t_group_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Boolean getRightType() {
		return rightType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group_right.right_type
	 * @param rightType  the value for t_group_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRightType(Boolean rightType) {
		this.rightType = rightType;
	}
}