package com.group12.salary.model;

import java.io.Serializable;

public class InterfaceDAO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String stme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.requrl
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String requrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.readyState
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String readystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.status
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.statusText
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String statustext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface.textStatus
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String textstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_interface
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.id
     *
     * @return the value of t_interface.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.id
     *
     * @param id the value for t_interface.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.path
     *
     * @return the value of t_interface.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.path
     *
     * @param path the value for t_interface.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.sTme
     *
     * @return the value of t_interface.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getStme() {
        return stme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.sTme
     *
     * @param stme the value for t_interface.sTme
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setStme(String stme) {
        this.stme = stme == null ? null : stme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.type
     *
     * @return the value of t_interface.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.type
     *
     * @param type the value for t_interface.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.requrl
     *
     * @return the value of t_interface.requrl
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getRequrl() {
        return requrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.requrl
     *
     * @param requrl the value for t_interface.requrl
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setRequrl(String requrl) {
        this.requrl = requrl == null ? null : requrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.readyState
     *
     * @return the value of t_interface.readyState
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getReadystate() {
        return readystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.readyState
     *
     * @param readystate the value for t_interface.readyState
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setReadystate(String readystate) {
        this.readystate = readystate == null ? null : readystate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.status
     *
     * @return the value of t_interface.status
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.status
     *
     * @param status the value for t_interface.status
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.statusText
     *
     * @return the value of t_interface.statusText
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getStatustext() {
        return statustext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.statusText
     *
     * @param statustext the value for t_interface.statusText
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setStatustext(String statustext) {
        this.statustext = statustext == null ? null : statustext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface.textStatus
     *
     * @return the value of t_interface.textStatus
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getTextstatus() {
        return textstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface.textStatus
     *
     * @param textstatus the value for t_interface.textStatus
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setTextstatus(String textstatus) {
        this.textstatus = textstatus == null ? null : textstatus.trim();
    }
}