package com.group12.salary.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationLogDAOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public OperationLogDAOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLogIdIsNull() {
			addCriterion("log_id is null");
			return (Criteria) this;
		}

		public Criteria andLogIdIsNotNull() {
			addCriterion("log_id is not null");
			return (Criteria) this;
		}

		public Criteria andLogIdEqualTo(Long value) {
			addCriterion("log_id =", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotEqualTo(Long value) {
			addCriterion("log_id <>", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThan(Long value) {
			addCriterion("log_id >", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanOrEqualTo(Long value) {
			addCriterion("log_id >=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThan(Long value) {
			addCriterion("log_id <", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanOrEqualTo(Long value) {
			addCriterion("log_id <=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdIn(List<Long> values) {
			addCriterion("log_id in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotIn(List<Long> values) {
			addCriterion("log_id not in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdBetween(Long value1, Long value2) {
			addCriterion("log_id between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotBetween(Long value1, Long value2) {
			addCriterion("log_id not between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andTableNameIsNull() {
			addCriterion("table_name is null");
			return (Criteria) this;
		}

		public Criteria andTableNameIsNotNull() {
			addCriterion("table_name is not null");
			return (Criteria) this;
		}

		public Criteria andTableNameEqualTo(String value) {
			addCriterion("table_name =", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotEqualTo(String value) {
			addCriterion("table_name <>", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameGreaterThan(String value) {
			addCriterion("table_name >", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameGreaterThanOrEqualTo(String value) {
			addCriterion("table_name >=", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLessThan(String value) {
			addCriterion("table_name <", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLessThanOrEqualTo(String value) {
			addCriterion("table_name <=", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameLike(String value) {
			addCriterion("table_name like", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotLike(String value) {
			addCriterion("table_name not like", value, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameIn(List<String> values) {
			addCriterion("table_name in", values, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotIn(List<String> values) {
			addCriterion("table_name not in", values, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameBetween(String value1, String value2) {
			addCriterion("table_name between", value1, value2, "tableName");
			return (Criteria) this;
		}

		public Criteria andTableNameNotBetween(String value1, String value2) {
			addCriterion("table_name not between", value1, value2, "tableName");
			return (Criteria) this;
		}

		public Criteria andColumnNameIsNull() {
			addCriterion("column_name is null");
			return (Criteria) this;
		}

		public Criteria andColumnNameIsNotNull() {
			addCriterion("column_name is not null");
			return (Criteria) this;
		}

		public Criteria andColumnNameEqualTo(String value) {
			addCriterion("column_name =", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameNotEqualTo(String value) {
			addCriterion("column_name <>", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameGreaterThan(String value) {
			addCriterion("column_name >", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
			addCriterion("column_name >=", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameLessThan(String value) {
			addCriterion("column_name <", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameLessThanOrEqualTo(String value) {
			addCriterion("column_name <=", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameLike(String value) {
			addCriterion("column_name like", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameNotLike(String value) {
			addCriterion("column_name not like", value, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameIn(List<String> values) {
			addCriterion("column_name in", values, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameNotIn(List<String> values) {
			addCriterion("column_name not in", values, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameBetween(String value1, String value2) {
			addCriterion("column_name between", value1, value2, "columnName");
			return (Criteria) this;
		}

		public Criteria andColumnNameNotBetween(String value1, String value2) {
			addCriterion("column_name not between", value1, value2, "columnName");
			return (Criteria) this;
		}

		public Criteria andChangeIdIsNull() {
			addCriterion("change_id is null");
			return (Criteria) this;
		}

		public Criteria andChangeIdIsNotNull() {
			addCriterion("change_id is not null");
			return (Criteria) this;
		}

		public Criteria andChangeIdEqualTo(String value) {
			addCriterion("change_id =", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotEqualTo(String value) {
			addCriterion("change_id <>", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdGreaterThan(String value) {
			addCriterion("change_id >", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdGreaterThanOrEqualTo(String value) {
			addCriterion("change_id >=", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLessThan(String value) {
			addCriterion("change_id <", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLessThanOrEqualTo(String value) {
			addCriterion("change_id <=", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdLike(String value) {
			addCriterion("change_id like", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotLike(String value) {
			addCriterion("change_id not like", value, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdIn(List<String> values) {
			addCriterion("change_id in", values, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotIn(List<String> values) {
			addCriterion("change_id not in", values, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdBetween(String value1, String value2) {
			addCriterion("change_id between", value1, value2, "changeId");
			return (Criteria) this;
		}

		public Criteria andChangeIdNotBetween(String value1, String value2) {
			addCriterion("change_id not between", value1, value2, "changeId");
			return (Criteria) this;
		}

		public Criteria andBeforeValueIsNull() {
			addCriterion("before_value is null");
			return (Criteria) this;
		}

		public Criteria andBeforeValueIsNotNull() {
			addCriterion("before_value is not null");
			return (Criteria) this;
		}

		public Criteria andBeforeValueEqualTo(String value) {
			addCriterion("before_value =", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueNotEqualTo(String value) {
			addCriterion("before_value <>", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueGreaterThan(String value) {
			addCriterion("before_value >", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueGreaterThanOrEqualTo(String value) {
			addCriterion("before_value >=", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueLessThan(String value) {
			addCriterion("before_value <", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueLessThanOrEqualTo(String value) {
			addCriterion("before_value <=", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueLike(String value) {
			addCriterion("before_value like", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueNotLike(String value) {
			addCriterion("before_value not like", value, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueIn(List<String> values) {
			addCriterion("before_value in", values, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueNotIn(List<String> values) {
			addCriterion("before_value not in", values, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueBetween(String value1, String value2) {
			addCriterion("before_value between", value1, value2, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andBeforeValueNotBetween(String value1, String value2) {
			addCriterion("before_value not between", value1, value2, "beforeValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueIsNull() {
			addCriterion("after_value is null");
			return (Criteria) this;
		}

		public Criteria andAfterValueIsNotNull() {
			addCriterion("after_value is not null");
			return (Criteria) this;
		}

		public Criteria andAfterValueEqualTo(String value) {
			addCriterion("after_value =", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueNotEqualTo(String value) {
			addCriterion("after_value <>", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueGreaterThan(String value) {
			addCriterion("after_value >", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueGreaterThanOrEqualTo(String value) {
			addCriterion("after_value >=", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueLessThan(String value) {
			addCriterion("after_value <", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueLessThanOrEqualTo(String value) {
			addCriterion("after_value <=", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueLike(String value) {
			addCriterion("after_value like", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueNotLike(String value) {
			addCriterion("after_value not like", value, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueIn(List<String> values) {
			addCriterion("after_value in", values, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueNotIn(List<String> values) {
			addCriterion("after_value not in", values, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueBetween(String value1, String value2) {
			addCriterion("after_value between", value1, value2, "afterValue");
			return (Criteria) this;
		}

		public Criteria andAfterValueNotBetween(String value1, String value2) {
			addCriterion("after_value not between", value1, value2, "afterValue");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeIsNull() {
			addCriterion("operation_datetime is null");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeIsNotNull() {
			addCriterion("operation_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeEqualTo(Date value) {
			addCriterion("operation_datetime =", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeNotEqualTo(Date value) {
			addCriterion("operation_datetime <>", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeGreaterThan(Date value) {
			addCriterion("operation_datetime >", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("operation_datetime >=", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeLessThan(Date value) {
			addCriterion("operation_datetime <", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("operation_datetime <=", value, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeIn(List<Date> values) {
			addCriterion("operation_datetime in", values, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeNotIn(List<Date> values) {
			addCriterion("operation_datetime not in", values, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeBetween(Date value1, Date value2) {
			addCriterion("operation_datetime between", value1, value2, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("operation_datetime not between", value1, value2, "operationDatetime");
			return (Criteria) this;
		}

		public Criteria andOperationTypeIsNull() {
			addCriterion("operation_type is null");
			return (Criteria) this;
		}

		public Criteria andOperationTypeIsNotNull() {
			addCriterion("operation_type is not null");
			return (Criteria) this;
		}

		public Criteria andOperationTypeEqualTo(Byte value) {
			addCriterion("operation_type =", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeNotEqualTo(Byte value) {
			addCriterion("operation_type <>", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeGreaterThan(Byte value) {
			addCriterion("operation_type >", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("operation_type >=", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeLessThan(Byte value) {
			addCriterion("operation_type <", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeLessThanOrEqualTo(Byte value) {
			addCriterion("operation_type <=", value, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeIn(List<Byte> values) {
			addCriterion("operation_type in", values, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeNotIn(List<Byte> values) {
			addCriterion("operation_type not in", values, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeBetween(Byte value1, Byte value2) {
			addCriterion("operation_type between", value1, value2, "operationType");
			return (Criteria) this;
		}

		public Criteria andOperationTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("operation_type not between", value1, value2, "operationType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_operation_log
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_operation_log
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 21 18:01:03 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}