package com.group12.salary.model;

import java.io.Serializable;

public class RightDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long rightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_right.right_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String rightName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_right.parent_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long parentRightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_right.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right.right_id
	 * @return  the value of t_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right.right_id
	 * @param rightId  the value for t_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right.right_name
	 * @return  the value of t_right.right_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getRightName() {
		return rightName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right.right_name
	 * @param rightName  the value for t_right.right_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRightName(String rightName) {
		this.rightName = rightName == null ? null : rightName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right.parent_right_id
	 * @return  the value of t_right.parent_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getParentRightId() {
		return parentRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right.parent_right_id
	 * @param parentRightId  the value for t_right.parent_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setParentRightId(Long parentRightId) {
		this.parentRightId = parentRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right.description
	 * @return  the value of t_right.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right.description
	 * @param description  the value for t_right.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}