package com.group12.salary.model;

import java.util.ArrayList;
import java.util.List;

public class RoleRightDAOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public RoleRightDAOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRoleRightIdIsNull() {
			addCriterion("role_right_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdIsNotNull() {
			addCriterion("role_right_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdEqualTo(Long value) {
			addCriterion("role_right_id =", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdNotEqualTo(Long value) {
			addCriterion("role_right_id <>", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdGreaterThan(Long value) {
			addCriterion("role_right_id >", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_right_id >=", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdLessThan(Long value) {
			addCriterion("role_right_id <", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdLessThanOrEqualTo(Long value) {
			addCriterion("role_right_id <=", value, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdIn(List<Long> values) {
			addCriterion("role_right_id in", values, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdNotIn(List<Long> values) {
			addCriterion("role_right_id not in", values, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdBetween(Long value1, Long value2) {
			addCriterion("role_right_id between", value1, value2, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleRightIdNotBetween(Long value1, Long value2) {
			addCriterion("role_right_id not between", value1, value2, "roleRightId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Long value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Long value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Long value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Long value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Long value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Long> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Long> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Long value1, Long value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Long value1, Long value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRightIdIsNull() {
			addCriterion("right_id is null");
			return (Criteria) this;
		}

		public Criteria andRightIdIsNotNull() {
			addCriterion("right_id is not null");
			return (Criteria) this;
		}

		public Criteria andRightIdEqualTo(Long value) {
			addCriterion("right_id =", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdNotEqualTo(Long value) {
			addCriterion("right_id <>", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdGreaterThan(Long value) {
			addCriterion("right_id >", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdGreaterThanOrEqualTo(Long value) {
			addCriterion("right_id >=", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdLessThan(Long value) {
			addCriterion("right_id <", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdLessThanOrEqualTo(Long value) {
			addCriterion("right_id <=", value, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdIn(List<Long> values) {
			addCriterion("right_id in", values, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdNotIn(List<Long> values) {
			addCriterion("right_id not in", values, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdBetween(Long value1, Long value2) {
			addCriterion("right_id between", value1, value2, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightIdNotBetween(Long value1, Long value2) {
			addCriterion("right_id not between", value1, value2, "rightId");
			return (Criteria) this;
		}

		public Criteria andRightTypeIsNull() {
			addCriterion("right_type is null");
			return (Criteria) this;
		}

		public Criteria andRightTypeIsNotNull() {
			addCriterion("right_type is not null");
			return (Criteria) this;
		}

		public Criteria andRightTypeEqualTo(Boolean value) {
			addCriterion("right_type =", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeNotEqualTo(Boolean value) {
			addCriterion("right_type <>", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeGreaterThan(Boolean value) {
			addCriterion("right_type >", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("right_type >=", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeLessThan(Boolean value) {
			addCriterion("right_type <", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("right_type <=", value, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeIn(List<Boolean> values) {
			addCriterion("right_type in", values, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeNotIn(List<Boolean> values) {
			addCriterion("right_type not in", values, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("right_type between", value1, value2, "rightType");
			return (Criteria) this;
		}

		public Criteria andRightTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("right_type not between", value1, value2, "rightType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_role_right
     *
     * @mbg.generated do_not_delete_during_merge Sat May 30 15:49:06 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}