package com.group12.salary.model;

import java.io.Serializable;

public class RoleDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.role_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.parent_role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long parentRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_role
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.role_id
	 * @return  the value of t_role.role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.role_id
	 * @param roleId  the value for t_role.role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.role_name
	 * @return  the value of t_role.role_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.role_name
	 * @param roleName  the value for t_role.role_name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.parent_role_id
	 * @return  the value of t_role.parent_role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getParentRoleId() {
		return parentRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.parent_role_id
	 * @param parentRoleId  the value for t_role.parent_role_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setParentRoleId(Long parentRoleId) {
		this.parentRoleId = parentRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.description
	 * @return  the value of t_role.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.description
	 * @param description  the value for t_role.description
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}