package com.group12.salary.model;

import java.io.Serializable;

public class RoleRightDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_right.role_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long roleRightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_right.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long rightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Boolean rightType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_role_right
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_right.role_right_id
	 * @return  the value of t_role_right.role_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRoleRightId() {
		return roleRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_right.role_right_id
	 * @param roleRightId  the value for t_role_right.role_right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRoleRightId(Long roleRightId) {
		this.roleRightId = roleRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_right.role_id
	 * @return  the value of t_role_right.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_right.role_id
	 * @param roleId  the value for t_role_right.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_right.right_id
	 * @return  the value of t_role_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_right.right_id
	 * @param rightId  the value for t_role_right.right_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_right.right_type
	 * @return  the value of t_role_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Boolean getRightType() {
		return rightType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_right.right_type
	 * @param rightType  the value for t_role_right.right_type
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRightType(Boolean rightType) {
		this.rightType = rightType;
	}
}