package com.group12.salary.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SalaryDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.year_month_date
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Date yearMonthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.name
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.base_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal baseSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.job_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal jobSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.working_age_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal workingAgeSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.food
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal food;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.coal
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal coal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.transport
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal transport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.subsidy1
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal subsidy1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.subsidy2
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal subsidy2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.sum_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal sumSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.room
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal room;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.water_electric
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal waterElectric;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.children
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal children;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.advance
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal advance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.other
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal other;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.deduct_total
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal deductTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.take_home_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private BigDecimal takeHomeSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_salary.status
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private int status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.id
	 * @return  the value of t_salary.id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.id
	 * @param id  the value for t_salary.id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.year_month_date
	 * @return  the value of t_salary.year_month_date
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Date getYearMonthDate() {
		return yearMonthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.year_month_date
	 * @param yearMonthDate  the value for t_salary.year_month_date
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setYearMonthDate(Date yearMonthDate) {
		this.yearMonthDate = yearMonthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.user_id
	 * @return  the value of t_salary.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.user_id
	 * @param userId  the value for t_salary.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.name
	 * @return  the value of t_salary.name
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.name
	 * @param name  the value for t_salary.name
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.base_salary
	 * @return  the value of t_salary.base_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getBaseSalary() {
		return baseSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.base_salary
	 * @param baseSalary  the value for t_salary.base_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setBaseSalary(BigDecimal baseSalary) {
		this.baseSalary = baseSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.job_salary
	 * @return  the value of t_salary.job_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getJobSalary() {
		return jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.job_salary
	 * @param jobSalary  the value for t_salary.job_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setJobSalary(BigDecimal jobSalary) {
		this.jobSalary = jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.working_age_salary
	 * @return  the value of t_salary.working_age_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getWorkingAgeSalary() {
		return workingAgeSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.working_age_salary
	 * @param workingAgeSalary  the value for t_salary.working_age_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setWorkingAgeSalary(BigDecimal workingAgeSalary) {
		this.workingAgeSalary = workingAgeSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.food
	 * @return  the value of t_salary.food
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getFood() {
		return food;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.food
	 * @param food  the value for t_salary.food
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setFood(BigDecimal food) {
		this.food = food;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.coal
	 * @return  the value of t_salary.coal
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getCoal() {
		return coal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.coal
	 * @param coal  the value for t_salary.coal
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setCoal(BigDecimal coal) {
		this.coal = coal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.transport
	 * @return  the value of t_salary.transport
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getTransport() {
		return transport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.transport
	 * @param transport  the value for t_salary.transport
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setTransport(BigDecimal transport) {
		this.transport = transport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.subsidy1
	 * @return  the value of t_salary.subsidy1
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getSubsidy1() {
		return subsidy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.subsidy1
	 * @param subsidy1  the value for t_salary.subsidy1
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setSubsidy1(BigDecimal subsidy1) {
		this.subsidy1 = subsidy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.subsidy2
	 * @return  the value of t_salary.subsidy2
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getSubsidy2() {
		return subsidy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.subsidy2
	 * @param subsidy2  the value for t_salary.subsidy2
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setSubsidy2(BigDecimal subsidy2) {
		this.subsidy2 = subsidy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.sum_salary
	 * @return  the value of t_salary.sum_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getSumSalary() {
		return sumSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.sum_salary
	 * @param sumSalary  the value for t_salary.sum_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setSumSalary(BigDecimal sumSalary) {
		this.sumSalary = sumSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.room
	 * @return  the value of t_salary.room
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getRoom() {
		return room;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.room
	 * @param room  the value for t_salary.room
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRoom(BigDecimal room) {
		this.room = room;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.water_electric
	 * @return  the value of t_salary.water_electric
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getWaterElectric() {
		return waterElectric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.water_electric
	 * @param waterElectric  the value for t_salary.water_electric
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setWaterElectric(BigDecimal waterElectric) {
		this.waterElectric = waterElectric;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.children
	 * @return  the value of t_salary.children
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getChildren() {
		return children;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.children
	 * @param children  the value for t_salary.children
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setChildren(BigDecimal children) {
		this.children = children;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.advance
	 * @return  the value of t_salary.advance
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getAdvance() {
		return advance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.advance
	 * @param advance  the value for t_salary.advance
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setAdvance(BigDecimal advance) {
		this.advance = advance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.other
	 * @return  the value of t_salary.other
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getOther() {
		return other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.other
	 * @param other  the value for t_salary.other
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setOther(BigDecimal other) {
		this.other = other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.deduct_total
	 * @return  the value of t_salary.deduct_total
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getDeductTotal() {
		return deductTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.deduct_total
	 * @param deductTotal  the value for t_salary.deduct_total
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setDeductTotal(BigDecimal deductTotal) {
		this.deductTotal = deductTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.take_home_salary
	 * @return  the value of t_salary.take_home_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public BigDecimal getTakeHomeSalary() {
		return takeHomeSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.take_home_salary
	 * @param takeHomeSalary  the value for t_salary.take_home_salary
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setTakeHomeSalary(BigDecimal takeHomeSalary) {
		this.takeHomeSalary = takeHomeSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_salary.status
	 * @return  the value of t_salary.status
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_salary.status
	 * @param status2  the value for t_salary.status
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setStatus(int status2) {
		this.status = status2;
	}
}