package com.group12.salary.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SubsidyDAOExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public SubsidyDAOExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andFoodIsNull() {
			addCriterion("food is null");
			return (Criteria) this;
		}

		public Criteria andFoodIsNotNull() {
			addCriterion("food is not null");
			return (Criteria) this;
		}

		public Criteria andFoodEqualTo(BigDecimal value) {
			addCriterion("food =", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodNotEqualTo(BigDecimal value) {
			addCriterion("food <>", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodGreaterThan(BigDecimal value) {
			addCriterion("food >", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("food >=", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodLessThan(BigDecimal value) {
			addCriterion("food <", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodLessThanOrEqualTo(BigDecimal value) {
			addCriterion("food <=", value, "food");
			return (Criteria) this;
		}

		public Criteria andFoodIn(List<BigDecimal> values) {
			addCriterion("food in", values, "food");
			return (Criteria) this;
		}

		public Criteria andFoodNotIn(List<BigDecimal> values) {
			addCriterion("food not in", values, "food");
			return (Criteria) this;
		}

		public Criteria andFoodBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("food between", value1, value2, "food");
			return (Criteria) this;
		}

		public Criteria andFoodNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("food not between", value1, value2, "food");
			return (Criteria) this;
		}

		public Criteria andCoalIsNull() {
			addCriterion("coal is null");
			return (Criteria) this;
		}

		public Criteria andCoalIsNotNull() {
			addCriterion("coal is not null");
			return (Criteria) this;
		}

		public Criteria andCoalEqualTo(BigDecimal value) {
			addCriterion("coal =", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalNotEqualTo(BigDecimal value) {
			addCriterion("coal <>", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalGreaterThan(BigDecimal value) {
			addCriterion("coal >", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("coal >=", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalLessThan(BigDecimal value) {
			addCriterion("coal <", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("coal <=", value, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalIn(List<BigDecimal> values) {
			addCriterion("coal in", values, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalNotIn(List<BigDecimal> values) {
			addCriterion("coal not in", values, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("coal between", value1, value2, "coal");
			return (Criteria) this;
		}

		public Criteria andCoalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("coal not between", value1, value2, "coal");
			return (Criteria) this;
		}

		public Criteria andTransportIsNull() {
			addCriterion("transport is null");
			return (Criteria) this;
		}

		public Criteria andTransportIsNotNull() {
			addCriterion("transport is not null");
			return (Criteria) this;
		}

		public Criteria andTransportEqualTo(BigDecimal value) {
			addCriterion("transport =", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportNotEqualTo(BigDecimal value) {
			addCriterion("transport <>", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportGreaterThan(BigDecimal value) {
			addCriterion("transport >", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("transport >=", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportLessThan(BigDecimal value) {
			addCriterion("transport <", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportLessThanOrEqualTo(BigDecimal value) {
			addCriterion("transport <=", value, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportIn(List<BigDecimal> values) {
			addCriterion("transport in", values, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportNotIn(List<BigDecimal> values) {
			addCriterion("transport not in", values, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("transport between", value1, value2, "transport");
			return (Criteria) this;
		}

		public Criteria andTransportNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("transport not between", value1, value2, "transport");
			return (Criteria) this;
		}

		public Criteria andSubsidy1IsNull() {
			addCriterion("subsidy1 is null");
			return (Criteria) this;
		}

		public Criteria andSubsidy1IsNotNull() {
			addCriterion("subsidy1 is not null");
			return (Criteria) this;
		}

		public Criteria andSubsidy1EqualTo(BigDecimal value) {
			addCriterion("subsidy1 =", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1NotEqualTo(BigDecimal value) {
			addCriterion("subsidy1 <>", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1GreaterThan(BigDecimal value) {
			addCriterion("subsidy1 >", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy1 >=", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1LessThan(BigDecimal value) {
			addCriterion("subsidy1 <", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1LessThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy1 <=", value, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1In(List<BigDecimal> values) {
			addCriterion("subsidy1 in", values, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1NotIn(List<BigDecimal> values) {
			addCriterion("subsidy1 not in", values, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy1 between", value1, value2, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy1NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy1 not between", value1, value2, "subsidy1");
			return (Criteria) this;
		}

		public Criteria andSubsidy2IsNull() {
			addCriterion("subsidy2 is null");
			return (Criteria) this;
		}

		public Criteria andSubsidy2IsNotNull() {
			addCriterion("subsidy2 is not null");
			return (Criteria) this;
		}

		public Criteria andSubsidy2EqualTo(BigDecimal value) {
			addCriterion("subsidy2 =", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2NotEqualTo(BigDecimal value) {
			addCriterion("subsidy2 <>", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2GreaterThan(BigDecimal value) {
			addCriterion("subsidy2 >", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy2 >=", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2LessThan(BigDecimal value) {
			addCriterion("subsidy2 <", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2LessThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy2 <=", value, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2In(List<BigDecimal> values) {
			addCriterion("subsidy2 in", values, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2NotIn(List<BigDecimal> values) {
			addCriterion("subsidy2 not in", values, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy2 between", value1, value2, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidy2NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy2 not between", value1, value2, "subsidy2");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalIsNull() {
			addCriterion("subsidy_total is null");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalIsNotNull() {
			addCriterion("subsidy_total is not null");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalEqualTo(BigDecimal value) {
			addCriterion("subsidy_total =", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalNotEqualTo(BigDecimal value) {
			addCriterion("subsidy_total <>", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalGreaterThan(BigDecimal value) {
			addCriterion("subsidy_total >", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy_total >=", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalLessThan(BigDecimal value) {
			addCriterion("subsidy_total <", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("subsidy_total <=", value, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalIn(List<BigDecimal> values) {
			addCriterion("subsidy_total in", values, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalNotIn(List<BigDecimal> values) {
			addCriterion("subsidy_total not in", values, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy_total between", value1, value2, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubsidyTotalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("subsidy_total not between", value1, value2, "subsidyTotal");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIsNull() {
			addCriterion("submit_user_id is null");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIsNotNull() {
			addCriterion("submit_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdEqualTo(String value) {
			addCriterion("submit_user_id =", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotEqualTo(String value) {
			addCriterion("submit_user_id <>", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdGreaterThan(String value) {
			addCriterion("submit_user_id >", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("submit_user_id >=", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLessThan(String value) {
			addCriterion("submit_user_id <", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLessThanOrEqualTo(String value) {
			addCriterion("submit_user_id <=", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdLike(String value) {
			addCriterion("submit_user_id like", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotLike(String value) {
			addCriterion("submit_user_id not like", value, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdIn(List<String> values) {
			addCriterion("submit_user_id in", values, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotIn(List<String> values) {
			addCriterion("submit_user_id not in", values, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdBetween(String value1, String value2) {
			addCriterion("submit_user_id between", value1, value2, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitUserIdNotBetween(String value1, String value2) {
			addCriterion("submit_user_id not between", value1, value2, "submitUserId");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIsNull() {
			addCriterion("submit_date is null");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIsNotNull() {
			addCriterion("submit_date is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitDateEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date =", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date <>", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateGreaterThan(Date value) {
			addCriterionForJDBCDate("submit_date >", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date >=", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateLessThan(Date value) {
			addCriterionForJDBCDate("submit_date <", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("submit_date <=", value, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateIn(List<Date> values) {
			addCriterionForJDBCDate("submit_date in", values, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("submit_date not in", values, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("submit_date between", value1, value2, "submitDate");
			return (Criteria) this;
		}

		public Criteria andSubmitDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("submit_date not between", value1, value2, "submitDate");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subsidy
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_subsidy
     *
     * @mbg.generated do_not_delete_during_merge Sat May 30 15:49:06 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}