package com.group12.salary.model;

import java.io.Serializable;

public class TimeDAO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.DNS
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String dns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.TCP
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String tcp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.WT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String wt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.DR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.ONL
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String onl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.ALLRT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String allrt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.PRDOM
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String prdom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_time.FXHR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private String fxhr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.id
     *
     * @return the value of t_time.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.id
     *
     * @param id the value for t_time.id
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.type
     *
     * @return the value of t_time.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.type
     *
     * @param type the value for t_time.type
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.path
     *
     * @return the value of t_time.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.path
     *
     * @param path the value for t_time.path
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.DNS
     *
     * @return the value of t_time.DNS
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getDns() {
        return dns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.DNS
     *
     * @param dns the value for t_time.DNS
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setDns(String dns) {
        this.dns = dns == null ? null : dns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.TCP
     *
     * @return the value of t_time.TCP
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getTcp() {
        return tcp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.TCP
     *
     * @param tcp the value for t_time.TCP
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setTcp(String tcp) {
        this.tcp = tcp == null ? null : tcp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.WT
     *
     * @return the value of t_time.WT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getWt() {
        return wt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.WT
     *
     * @param wt the value for t_time.WT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setWt(String wt) {
        this.wt = wt == null ? null : wt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.DR
     *
     * @return the value of t_time.DR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.DR
     *
     * @param dr the value for t_time.DR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.ONL
     *
     * @return the value of t_time.ONL
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getOnl() {
        return onl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.ONL
     *
     * @param onl the value for t_time.ONL
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setOnl(String onl) {
        this.onl = onl == null ? null : onl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.ALLRT
     *
     * @return the value of t_time.ALLRT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getAllrt() {
        return allrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.ALLRT
     *
     * @param allrt the value for t_time.ALLRT
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setAllrt(String allrt) {
        this.allrt = allrt == null ? null : allrt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.PRDOM
     *
     * @return the value of t_time.PRDOM
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getPrdom() {
        return prdom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.PRDOM
     *
     * @param prdom the value for t_time.PRDOM
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setPrdom(String prdom) {
        this.prdom = prdom == null ? null : prdom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_time.FXHR
     *
     * @return the value of t_time.FXHR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getFxhr() {
        return fxhr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_time.FXHR
     *
     * @param fxhr the value for t_time.FXHR
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setFxhr(String fxhr) {
        this.fxhr = fxhr == null ? null : fxhr.trim();
    }
}