package com.group12.salary.model;

import java.util.ArrayList;
import java.util.List;

public class TimeDAOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public TimeDAOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("path is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("path is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(String value) {
            addCriterion("path =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(String value) {
            addCriterion("path <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(String value) {
            addCriterion("path >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(String value) {
            addCriterion("path >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(String value) {
            addCriterion("path <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(String value) {
            addCriterion("path <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLike(String value) {
            addCriterion("path like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotLike(String value) {
            addCriterion("path not like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<String> values) {
            addCriterion("path in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<String> values) {
            addCriterion("path not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(String value1, String value2) {
            addCriterion("path between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(String value1, String value2) {
            addCriterion("path not between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andDnsIsNull() {
            addCriterion("DNS is null");
            return (Criteria) this;
        }

        public Criteria andDnsIsNotNull() {
            addCriterion("DNS is not null");
            return (Criteria) this;
        }

        public Criteria andDnsEqualTo(String value) {
            addCriterion("DNS =", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsNotEqualTo(String value) {
            addCriterion("DNS <>", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsGreaterThan(String value) {
            addCriterion("DNS >", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsGreaterThanOrEqualTo(String value) {
            addCriterion("DNS >=", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsLessThan(String value) {
            addCriterion("DNS <", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsLessThanOrEqualTo(String value) {
            addCriterion("DNS <=", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsLike(String value) {
            addCriterion("DNS like", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsNotLike(String value) {
            addCriterion("DNS not like", value, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsIn(List<String> values) {
            addCriterion("DNS in", values, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsNotIn(List<String> values) {
            addCriterion("DNS not in", values, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsBetween(String value1, String value2) {
            addCriterion("DNS between", value1, value2, "dns");
            return (Criteria) this;
        }

        public Criteria andDnsNotBetween(String value1, String value2) {
            addCriterion("DNS not between", value1, value2, "dns");
            return (Criteria) this;
        }

        public Criteria andTcpIsNull() {
            addCriterion("TCP is null");
            return (Criteria) this;
        }

        public Criteria andTcpIsNotNull() {
            addCriterion("TCP is not null");
            return (Criteria) this;
        }

        public Criteria andTcpEqualTo(String value) {
            addCriterion("TCP =", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpNotEqualTo(String value) {
            addCriterion("TCP <>", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpGreaterThan(String value) {
            addCriterion("TCP >", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpGreaterThanOrEqualTo(String value) {
            addCriterion("TCP >=", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpLessThan(String value) {
            addCriterion("TCP <", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpLessThanOrEqualTo(String value) {
            addCriterion("TCP <=", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpLike(String value) {
            addCriterion("TCP like", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpNotLike(String value) {
            addCriterion("TCP not like", value, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpIn(List<String> values) {
            addCriterion("TCP in", values, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpNotIn(List<String> values) {
            addCriterion("TCP not in", values, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpBetween(String value1, String value2) {
            addCriterion("TCP between", value1, value2, "tcp");
            return (Criteria) this;
        }

        public Criteria andTcpNotBetween(String value1, String value2) {
            addCriterion("TCP not between", value1, value2, "tcp");
            return (Criteria) this;
        }

        public Criteria andWtIsNull() {
            addCriterion("WT is null");
            return (Criteria) this;
        }

        public Criteria andWtIsNotNull() {
            addCriterion("WT is not null");
            return (Criteria) this;
        }

        public Criteria andWtEqualTo(String value) {
            addCriterion("WT =", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtNotEqualTo(String value) {
            addCriterion("WT <>", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtGreaterThan(String value) {
            addCriterion("WT >", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtGreaterThanOrEqualTo(String value) {
            addCriterion("WT >=", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtLessThan(String value) {
            addCriterion("WT <", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtLessThanOrEqualTo(String value) {
            addCriterion("WT <=", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtLike(String value) {
            addCriterion("WT like", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtNotLike(String value) {
            addCriterion("WT not like", value, "wt");
            return (Criteria) this;
        }

        public Criteria andWtIn(List<String> values) {
            addCriterion("WT in", values, "wt");
            return (Criteria) this;
        }

        public Criteria andWtNotIn(List<String> values) {
            addCriterion("WT not in", values, "wt");
            return (Criteria) this;
        }

        public Criteria andWtBetween(String value1, String value2) {
            addCriterion("WT between", value1, value2, "wt");
            return (Criteria) this;
        }

        public Criteria andWtNotBetween(String value1, String value2) {
            addCriterion("WT not between", value1, value2, "wt");
            return (Criteria) this;
        }

        public Criteria andDrIsNull() {
            addCriterion("DR is null");
            return (Criteria) this;
        }

        public Criteria andDrIsNotNull() {
            addCriterion("DR is not null");
            return (Criteria) this;
        }

        public Criteria andDrEqualTo(String value) {
            addCriterion("DR =", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotEqualTo(String value) {
            addCriterion("DR <>", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThan(String value) {
            addCriterion("DR >", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThanOrEqualTo(String value) {
            addCriterion("DR >=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThan(String value) {
            addCriterion("DR <", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThanOrEqualTo(String value) {
            addCriterion("DR <=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLike(String value) {
            addCriterion("DR like", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotLike(String value) {
            addCriterion("DR not like", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrIn(List<String> values) {
            addCriterion("DR in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotIn(List<String> values) {
            addCriterion("DR not in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrBetween(String value1, String value2) {
            addCriterion("DR between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotBetween(String value1, String value2) {
            addCriterion("DR not between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andOnlIsNull() {
            addCriterion("ONL is null");
            return (Criteria) this;
        }

        public Criteria andOnlIsNotNull() {
            addCriterion("ONL is not null");
            return (Criteria) this;
        }

        public Criteria andOnlEqualTo(String value) {
            addCriterion("ONL =", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlNotEqualTo(String value) {
            addCriterion("ONL <>", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlGreaterThan(String value) {
            addCriterion("ONL >", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlGreaterThanOrEqualTo(String value) {
            addCriterion("ONL >=", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlLessThan(String value) {
            addCriterion("ONL <", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlLessThanOrEqualTo(String value) {
            addCriterion("ONL <=", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlLike(String value) {
            addCriterion("ONL like", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlNotLike(String value) {
            addCriterion("ONL not like", value, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlIn(List<String> values) {
            addCriterion("ONL in", values, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlNotIn(List<String> values) {
            addCriterion("ONL not in", values, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlBetween(String value1, String value2) {
            addCriterion("ONL between", value1, value2, "onl");
            return (Criteria) this;
        }

        public Criteria andOnlNotBetween(String value1, String value2) {
            addCriterion("ONL not between", value1, value2, "onl");
            return (Criteria) this;
        }

        public Criteria andAllrtIsNull() {
            addCriterion("ALLRT is null");
            return (Criteria) this;
        }

        public Criteria andAllrtIsNotNull() {
            addCriterion("ALLRT is not null");
            return (Criteria) this;
        }

        public Criteria andAllrtEqualTo(String value) {
            addCriterion("ALLRT =", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtNotEqualTo(String value) {
            addCriterion("ALLRT <>", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtGreaterThan(String value) {
            addCriterion("ALLRT >", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtGreaterThanOrEqualTo(String value) {
            addCriterion("ALLRT >=", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtLessThan(String value) {
            addCriterion("ALLRT <", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtLessThanOrEqualTo(String value) {
            addCriterion("ALLRT <=", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtLike(String value) {
            addCriterion("ALLRT like", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtNotLike(String value) {
            addCriterion("ALLRT not like", value, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtIn(List<String> values) {
            addCriterion("ALLRT in", values, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtNotIn(List<String> values) {
            addCriterion("ALLRT not in", values, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtBetween(String value1, String value2) {
            addCriterion("ALLRT between", value1, value2, "allrt");
            return (Criteria) this;
        }

        public Criteria andAllrtNotBetween(String value1, String value2) {
            addCriterion("ALLRT not between", value1, value2, "allrt");
            return (Criteria) this;
        }

        public Criteria andPrdomIsNull() {
            addCriterion("PRDOM is null");
            return (Criteria) this;
        }

        public Criteria andPrdomIsNotNull() {
            addCriterion("PRDOM is not null");
            return (Criteria) this;
        }

        public Criteria andPrdomEqualTo(String value) {
            addCriterion("PRDOM =", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomNotEqualTo(String value) {
            addCriterion("PRDOM <>", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomGreaterThan(String value) {
            addCriterion("PRDOM >", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomGreaterThanOrEqualTo(String value) {
            addCriterion("PRDOM >=", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomLessThan(String value) {
            addCriterion("PRDOM <", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomLessThanOrEqualTo(String value) {
            addCriterion("PRDOM <=", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomLike(String value) {
            addCriterion("PRDOM like", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomNotLike(String value) {
            addCriterion("PRDOM not like", value, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomIn(List<String> values) {
            addCriterion("PRDOM in", values, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomNotIn(List<String> values) {
            addCriterion("PRDOM not in", values, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomBetween(String value1, String value2) {
            addCriterion("PRDOM between", value1, value2, "prdom");
            return (Criteria) this;
        }

        public Criteria andPrdomNotBetween(String value1, String value2) {
            addCriterion("PRDOM not between", value1, value2, "prdom");
            return (Criteria) this;
        }

        public Criteria andFxhrIsNull() {
            addCriterion("FXHR is null");
            return (Criteria) this;
        }

        public Criteria andFxhrIsNotNull() {
            addCriterion("FXHR is not null");
            return (Criteria) this;
        }

        public Criteria andFxhrEqualTo(String value) {
            addCriterion("FXHR =", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrNotEqualTo(String value) {
            addCriterion("FXHR <>", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrGreaterThan(String value) {
            addCriterion("FXHR >", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrGreaterThanOrEqualTo(String value) {
            addCriterion("FXHR >=", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrLessThan(String value) {
            addCriterion("FXHR <", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrLessThanOrEqualTo(String value) {
            addCriterion("FXHR <=", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrLike(String value) {
            addCriterion("FXHR like", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrNotLike(String value) {
            addCriterion("FXHR not like", value, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrIn(List<String> values) {
            addCriterion("FXHR in", values, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrNotIn(List<String> values) {
            addCriterion("FXHR not in", values, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrBetween(String value1, String value2) {
            addCriterion("FXHR between", value1, value2, "fxhr");
            return (Criteria) this;
        }

        public Criteria andFxhrNotBetween(String value1, String value2) {
            addCriterion("FXHR not between", value1, value2, "fxhr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_time
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_time
     *
     * @mbg.generated Wed Jun 10 10:14:28 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}