package com.group12.salary.model;

import java.io.Serializable;

public class UserDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.email
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.telephone
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.bank_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String bankCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.department_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.title
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.working_age
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Integer workingAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.degree
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String degree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.nation
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String nation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.origin
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_id
	 * @return  the value of t_user.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_id
	 * @param userId  the value for t_user.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.email
	 * @return  the value of t_user.email
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.email
	 * @param email  the value for t_user.email
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.telephone
	 * @return  the value of t_user.telephone
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.telephone
	 * @param telephone  the value for t_user.telephone
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.bank_card
	 * @return  the value of t_user.bank_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getBankCard() {
		return bankCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.bank_card
	 * @param bankCard  the value for t_user.bank_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setBankCard(String bankCard) {
		this.bankCard = bankCard == null ? null : bankCard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.department_id
	 * @return  the value of t_user.department_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.department_id
	 * @param departmentId  the value for t_user.department_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId == null ? null : departmentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.title
	 * @return  the value of t_user.title
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.title
	 * @param title  the value for t_user.title
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.working_age
	 * @return  the value of t_user.working_age
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Integer getWorkingAge() {
		return workingAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.working_age
	 * @param workingAge  the value for t_user.working_age
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setWorkingAge(Integer workingAge) {
		this.workingAge = workingAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.degree
	 * @return  the value of t_user.degree
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getDegree() {
		return degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.degree
	 * @param degree  the value for t_user.degree
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setDegree(String degree) {
		this.degree = degree == null ? null : degree.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.nation
	 * @return  the value of t_user.nation
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.nation
	 * @param nation  the value for t_user.nation
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setNation(String nation) {
		this.nation = nation == null ? null : nation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.origin
	 * @return  the value of t_user.origin
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.origin
	 * @param origin  the value for t_user.origin
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setOrigin(String origin) {
		this.origin = origin == null ? null : origin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id_card
	 * @return  the value of t_user.id_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id_card
	 * @param idCard  the value for t_user.id_card
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard == null ? null : idCard.trim();
	}
}