package com.group12.salary.model;

import java.io.Serializable;

public class UserRightDAO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_right.user_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long userRightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_right.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Long rightId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_right.right_type
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private Boolean rightType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_right
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_right.user_right_id
	 * @return  the value of t_user_right.user_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getUserRightId() {
		return userRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_right.user_right_id
	 * @param userRightId  the value for t_user_right.user_right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setUserRightId(Long userRightId) {
		this.userRightId = userRightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_right.user_id
	 * @return  the value of t_user_right.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_right.user_id
	 * @param userId  the value for t_user_right.user_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_right.right_id
	 * @return  the value of t_user_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Long getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_right.right_id
	 * @param rightId  the value for t_user_right.right_id
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_right.right_type
	 * @return  the value of t_user_right.right_type
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public Boolean getRightType() {
		return rightType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_right.right_type
	 * @param rightType  the value for t_user_right.right_type
	 * @mbg.generated  Sat May 30 16:46:21 GMT+08:00 2020
	 */
	public void setRightType(Boolean rightType) {
		this.rightType = rightType;
	}
}