package com.group12.salary.model;

import java.io.Serializable;

public class UserRole implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.user_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long userRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_role
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.user_role_id
	 * @return  the value of t_user_role.user_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getUserRoleId() {
		return userRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.user_role_id
	 * @param userRoleId  the value for t_user_role.user_role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setUserRoleId(Long userRoleId) {
		this.userRoleId = userRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.user_id
	 * @return  the value of t_user_role.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.user_id
	 * @param userId  the value for t_user_role.user_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_role.role_id
	 * @return  the value of t_user_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_role.role_id
	 * @param roleId  the value for t_user_role.role_id
	 * @mbg.generated  Sat May 02 09:47:09 GMT+08:00 2020
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}